### ISSUE TITLE
JOSS 1: Community guidelines

### ISSUE THREAD

**Issue by dlagrava** [roshansamuel/saras#1]
Hello,

In order to be accepted as a JOSS submission, there need to be clear guidelines on how to contribute or report bugs to the repository. Could you please add this to the README?

Thanks,
Daniel

**Comment by roshansamuel** [comment]
Hi,

Thank you for pointing this out. In commit 0d5034e to master, we have updated the README with guidelines for contributing and reporting bugs. Can this issue be marked as closed?

Thanks,

Roshan

**Comment by dlagrava** [comment]
Hello,

That looks good. Closing.

Regards,
Daniel
