### ISSUE TITLE
JOSS 2: Documentation on how to write examples

### ISSUE THREAD

**Issue by dlagrava** [roshansamuel/saras#2]
Hello,

I have been reviewing your software. I understand that there are 2 tests that you can run. You can see some of the declarations to make a test there. However, I do not see any documentation on how to write my own example: it would be good to have an document that says how to setup a 2D/3D simulation, how to set the boundary conditions etc.

Cheers,
Daniel

**Comment by roshansamuel** [comment]
Hi,

Thank you for helping us improve the documentation of the solver. In the commit 147c174 to master, we have added a new section to the README.md file, titled [Setting up a new case in SARAS](https://github.com/roshansamuel/saras#setting-up-a-new-case-in-saras).

We hope that the instructions in this section will be sufficient for the user to write their own examples with SARAS. If you feel that this addresses the issue adequately, please mark this issue as closed.

Thanks!

Roshan

**Comment by dlagrava** [comment]
Hello Roshan,

That looks good. I will close this ticket.

Cheers,
Daniel
